/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form.order;

import domain.OrderItem;
import domain.Product;
import form.components.IMyForm;
import form.components.MyForm;
import form.product.PanelSearchProduct;
import java.awt.Window;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import logic.Controler;
import session.Session;

/**
 *
 * @author Rados
 */
public class PanelNewOrderItem extends javax.swing.JPanel {

    private JDialog ancestor;
    private PanelSearchProduct panelSearchProduct;

    /**
     * Creates new form PanelNewOrderItem
     */

    PanelNewOrderItem(JDialog ancestor) {

        this.ancestor = ancestor;
        Controler.getInstance().getFormMain().setPanelNewOrderItem(this);
        initComponents();
        prepareForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblPriceProduct = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        txtQuantity = new javax.swing.JTextField();
        txtPriceProduct = new javax.swing.JTextField();
        txtProduct = new javax.swing.JTextField();
        btnSelectProduct = new javax.swing.JButton();

        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        jLabel1.setText("Proizvod:");

        jLabel2.setText("Količina:");

        lblPriceProduct.setText("Cena:");

        btnCancel.setText("Odustani");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnAdd.setText("Dodaj");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnSelectProduct.setText("Izaberi proizvod");
        btnSelectProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectProductActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(lblPriceProduct))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQuantity)
                            .addComponent(txtPriceProduct))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnSelectProduct)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelectProduct))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPriceProduct)
                    .addComponent(txtPriceProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnAdd))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        cancel();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSelectProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectProductActionPerformed
        Session.getInstance().getUseCaseParams().put("request manufacturer", "PanelSelectProduct");
        Session.getInstance().getUseCaseParams().put("request type", "PanelSelectProduct");
        Session.getInstance().getUseCaseParams().put("request product", "PanelSelectProduct");
        Session.getInstance().getUseCaseParams().put("panelNewOrderItem", this);

        Session.getInstance().setCurrentUseCase("Select product");
        txtQuantity.setText("");
        panelSearchProduct = new PanelSearchProduct(ancestor);
        panelSearchProduct.setBtn();
        JDialog dialog = new MyForm(panelSearchProduct, "Pretraga i izbor proizvoda", true);
        dialog.add(panelSearchProduct);

        Controler.getInstance().setCurrentForm((IMyForm) dialog);
        prepareDialog(dialog);
    }//GEN-LAST:event_btnSelectProductActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            validation();
            int quantity = Integer.parseInt(txtQuantity.getText().trim());
            double priceProduct = Double.parseDouble(txtPriceProduct.getText());
            double price = priceProduct * quantity;
            Product product = (Product) Session.getInstance().getUseCaseParams().get("selectedProduct");
            OrderItem oi = new OrderItem(null, -1, product, quantity, price);

            IMyForm imf = Controler.getInstance().getCurrentForm();
            PanelNewOrder panel = (PanelNewOrder) Session.getInstance().getUseCaseParams().get("panelNewOrder");

            panel.addOrderItem(oi);

            ((JDialog)imf).dispose();
            //Controler.getInstance().setCurrentForm(null);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

    }//GEN-LAST:event_btnAddActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        JOptionPane.showMessageDialog(null, "Activated");
    }//GEN-LAST:event_formFocusGained

    public PanelSearchProduct getPanelSearchProduct() {
        return panelSearchProduct;
    }

    public void setPanelSearchProduct(PanelSearchProduct panelSearchProduct) {
        this.panelSearchProduct = panelSearchProduct;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSelectProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblPriceProduct;
    private javax.swing.JTextField txtPriceProduct;
    private javax.swing.JTextField txtProduct;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables

    private void cancel() {
        //Controler.getInstance().setActiveWindow((Window) ancestor);
        //((JPanel)Controler.getInstance().getCurrentForm().getMyPanel()).setVisible(false);
        ((JDialog)Controler.getInstance().getCurrentForm()).dispose();
    }

    private void prepareForm() {
        txtProduct.setEditable(false);
        txtPriceProduct.setEditable(false);
    }

    private void validation() throws Exception {
        if (txtQuantity.getText().isEmpty() || txtQuantity.getText().equals("")) {
            throw new Exception("Nije uneta količina!");
        } else if (Integer.parseInt(txtQuantity.getText().trim()) <= 0) {
            throw new Exception("Količina mora biti veća od 0!");
        }

        if (txtProduct.getText().isEmpty() || txtProduct.getText().equals("")) {
            throw new Exception("Niste uneli proizvod!");
        }

    }

    private void prepareDialog(JDialog dialog) {
        Controler.getInstance().setActiveWindow(dialog);

        dialog.pack();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }

    public void fillProduct(Product product) {
        txtProduct.setText(product+"");
        txtPriceProduct.setText(product.getPrice() + "");
    }

}
