/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import communication.Communication;
import constants.Operation;
import domain.Product;
import domain.Seller;
import form.client.PanelClient;
import form.client.PanelSearchClient;
import form.order.PanelNewOrder;
import form.order.PanelNewOrderItem;
import form.order.PanelOrders;
import form.product.PanelProduct;
import form.product.PanelSearchProduct;
import form.product.model.TableModelProduct;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import logic.Controler;
import session.Session;
import threads.ClockThread;
import transfer.ClientRequest;

/**
 *
 * @author Rados
 */
public final class FormMain extends javax.swing.JFrame {

    private PanelProduct panelProduct;
    private PanelSearchProduct panelSearchProduct;
    private TableModelProduct modelProduct;
    private PanelClient panelClient;
    private PanelSearchClient panelSearchClient;
    private PanelOrders panelOrders;
    private PanelNewOrder panelNewOrder;
    private PanelNewOrderItem panelNewOrderItem;
    private Seller seller;
    
    /**
     * Creates new form GlavnaForma
     */
    public FormMain() {
        initComponents();
        Controler.getInstance().setActiveWindow(this);
        startClock();
        setModelP();
        requestProductsForTable();
        adjustTableProduct();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSeller = new javax.swing.JLabel();
        lblClock = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProducts = new javax.swing.JTable();
        lblProducts = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmSearchProducts = new javax.swing.JMenu();
        jmiNewProduct = new javax.swing.JMenuItem();
        jmiSearchProducts = new javax.swing.JMenuItem();
        jmClient = new javax.swing.JMenu();
        jmiNewClient = new javax.swing.JMenuItem();
        jmiSearchClients = new javax.swing.JMenuItem();
        jmOrder = new javax.swing.JMenu();
        jmiOrder = new javax.swing.JMenuItem();
        jmSeller = new javax.swing.JMenu();
        jmiLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Online mobile shop");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblSeller.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblSeller.setText("Prodavac: ");

        lblClock.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblClock.setText("Sat:");

        tblProducts.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblProducts);

        lblProducts.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblProducts.setText("Proizvodi:");

        jmSearchProducts.setText("Proizvod ");

        jmiNewProduct.setText("Novi");
        jmiNewProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNewProductActionPerformed(evt);
            }
        });
        jmSearchProducts.add(jmiNewProduct);

        jmiSearchProducts.setText("Pretrazi");
        jmiSearchProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSearchProductsActionPerformed(evt);
            }
        });
        jmSearchProducts.add(jmiSearchProducts);

        jMenuBar1.add(jmSearchProducts);

        jmClient.setText("Naručilac");

        jmiNewClient.setText("Novi");
        jmiNewClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNewClientActionPerformed(evt);
            }
        });
        jmClient.add(jmiNewClient);

        jmiSearchClients.setText("Pretrazi");
        jmiSearchClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSearchClientsActionPerformed(evt);
            }
        });
        jmClient.add(jmiSearchClients);

        jMenuBar1.add(jmClient);

        jmOrder.setText("Narudžbe");

        jmiOrder.setText("Pregled");
        jmiOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiOrderActionPerformed(evt);
            }
        });
        jmOrder.add(jmiOrder);

        jMenuBar1.add(jmOrder);

        jmSeller.setText("Prodavac");

        jmiLogout.setText("Logout");
        jmiLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiLogoutActionPerformed(evt);
            }
        });
        jmSeller.add(jmiLogout);

        jMenuBar1.add(jmSeller);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSeller)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 416, Short.MAX_VALUE)
                        .addComponent(lblClock)
                        .addGap(66, 66, 66))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblProducts)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSeller)
                    .addComponent(lblClock))
                .addGap(66, 66, 66)
                .addComponent(lblProducts)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(218, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiNewProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNewProductActionPerformed
        JDialog dialog = new JDialog(this, "Unos novog proizvoda", true);

        panelProduct = new PanelProduct(FormMode.NEW, dialog);
        dialog.add(panelProduct);
        prepareDialog(dialog);
    }//GEN-LAST:event_jmiNewProductActionPerformed

    private void jmiSearchProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSearchProductsActionPerformed
        JDialog dialog = new JDialog(this, "Pretraga proizvoda", true);

        Session.getInstance().setCurrentUseCase("Search products");
        panelSearchProduct = new PanelSearchProduct(dialog);
        dialog.add(panelSearchProduct);
        prepareDialog(dialog);
    }//GEN-LAST:event_jmiSearchProductsActionPerformed

    private void jmiNewClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNewClientActionPerformed
        JDialog dialog = new JDialog(this, "Unos novog naručioca", true);
        
        panelClient = new PanelClient(FormMode.NEW, dialog);
        dialog.add(panelClient);
        prepareDialog(dialog);
    }//GEN-LAST:event_jmiNewClientActionPerformed

    private void jmiSearchClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSearchClientsActionPerformed
        JDialog dialog = new JDialog(this, "Pretraga naručilaca", true);

        Session.getInstance().setCurrentUseCase("Search clients");
        panelSearchClient = new PanelSearchClient(dialog);
        dialog.add(panelSearchClient);
        prepareDialog(dialog);
    }//GEN-LAST:event_jmiSearchClientsActionPerformed

    private void jmiOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiOrderActionPerformed
        JDialog dialog = new JDialog(this, "Pregled narudžba", true);

        panelOrders = new PanelOrders(dialog);
        dialog.add(panelOrders);
        prepareDialog(dialog);
    }//GEN-LAST:event_jmiOrderActionPerformed

    private void jmiLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiLogoutActionPerformed
        requestLogout();
    }//GEN-LAST:event_jmiLogoutActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        requestLogout();
    }//GEN-LAST:event_formWindowClosing

    public PanelProduct getPanelProduct() {
        return panelProduct;
    }

    public PanelSearchProduct getPanelSearchProduct() {
        return panelSearchProduct;
    }

    public void setPanelSearchProduct(PanelSearchProduct panelSearchProduct) {
        this.panelSearchProduct = panelSearchProduct;
    }

    public void setPanelProduct(PanelProduct panelProduct) {
        this.panelProduct = panelProduct;
    }

    public TableModelProduct getModelProduct() {
        return modelProduct;
    }

    public void setModelProduct(TableModelProduct modelProduct) {
        this.modelProduct = modelProduct;
        tblProducts.setModel(modelProduct);
    }

    public PanelClient getPanelClient() {
        return panelClient;
    }

    public void setPanelClient(PanelClient panelClient) {
        this.panelClient = panelClient;
    }

     public PanelSearchClient getPanelSearchClient() {
        return panelSearchClient;
    }

    public void setPanelSearchClient(PanelSearchClient panelSearchClient) {
        this.panelSearchClient = panelSearchClient;
    }

    public PanelOrders getPanelOrders() {
        return panelOrders;
    }

    public void setPanelOrders(PanelOrders panelOrders) {
        this.panelOrders = panelOrders;
    }

    public PanelNewOrder getPanelNewOrder() {
        return panelNewOrder;
    }

    public void setPanelNewOrder(PanelNewOrder panelNewOrder) {
        this.panelNewOrder = panelNewOrder;
    }

    public PanelNewOrderItem getPanelNewOrderItem() {
        return panelNewOrderItem;
    }

    public void setPanelNewOrderItem(PanelNewOrderItem panelNewOrderItem) {
        this.panelNewOrderItem = panelNewOrderItem;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu jmClient;
    private javax.swing.JMenu jmOrder;
    private javax.swing.JMenu jmSearchProducts;
    private javax.swing.JMenu jmSeller;
    private javax.swing.JMenuItem jmiLogout;
    private javax.swing.JMenuItem jmiNewClient;
    private javax.swing.JMenuItem jmiNewProduct;
    private javax.swing.JMenuItem jmiOrder;
    private javax.swing.JMenuItem jmiSearchClients;
    private javax.swing.JMenuItem jmiSearchProducts;
    private javax.swing.JLabel lblClock;
    private javax.swing.JLabel lblProducts;
    private javax.swing.JLabel lblSeller;
    private javax.swing.JTable tblProducts;
    // End of variables declaration//GEN-END:variables

    public void setSeller(Seller seller) {
        this.seller = seller;
        lblSeller.setText("Prodavac: " + seller.getName() + " " + seller.getSurname());
    }

    public Seller getSeller() {
        return seller;
    }
    
    public void logout(boolean successful) {
        String message;
        if (successful) {
            message = "Uspesno ste se odjavili";
        } else {
            message = "Veza sa serverom je prekinuta";
        }
        JOptionPane.showMessageDialog(this, message);
    }

    private void requestLogout() {
        ClientRequest cr = new ClientRequest();
        Seller s = Session.getInstance().getLoggedSeller();
        cr.setParameter(s);
        cr.setOperation(Operation.LOGOUT);
        Communication.getInstance().sendRequest(cr);
    }

    private void startClock() {
        ClockThread ct = new ClockThread(lblClock);
        ct.start();
    }

    private void setModelP() {
        ArrayList<Product> products = new ArrayList<>();
        TableModelProduct tcm = new TableModelProduct(products);
        modelProduct = tcm;
        tblProducts.setModel(modelProduct);
    }

    public void requestProductsForTable() {
        ClientRequest cr = new ClientRequest();
        Session.getInstance().getUseCaseParams().put("request product", "FormMain");
        cr.setOperation(Operation.GET_ALL_PRODUCTS);
        Communication.getInstance().sendRequest(cr);
    }

    private void adjustTableProduct() {
        TableColumn column = null;
        for (int i = 0; i < modelProduct.getColumnCount(); i++) {
            column = tblProducts.getColumnModel().getColumn(i);
            switch (i) {
                case 0:
                    column.setPreferredWidth(37);
                    break;
                case 1:
                    column.setPreferredWidth(100);
                    break;
                case 2:
                    column.setPreferredWidth(60);
                    break;
                case 3:
                    column.setPreferredWidth(100);
                    break;
            }
        }
    }

    private void prepareDialog(JDialog dialog) {
        Controler.getInstance().setActiveWindow(dialog);

        dialog.pack();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }



}
